### ISSUE TITLE
4K->2K Support

### ISSUE THREAD

**Issue by designgears** [braintapper/ezcoo-hdmi-switch#1]
I noticed on their site they mention it can only do 4K->1080p scaling, with your tool are you to switch output to 1440p(2K)? or is that typo?

**Comment by designgears** [comment]
Actually after looking more at their site they're incorrectly calling 1080p 2K. bummer. 

![430ea9660f](https://user-images.githubusercontent.com/799451/165140732-e3945049-5ebf-4b8f-af9d-d46679f900a9.jpg)

**Comment by braintapper** [comment]
I am using one to switch between a pair of 4K/60 monitors between two computers, and another to switch between a pair of 1080p monitors between the same two computers. I do not really use alternative resolutions or scaling.

**Comment by braintapper** [comment]
Having said that, I think you can override the dip switch via the USB connection (which I do not do, because I don't need to).
